import contentData from "@/data/content.json";

export const SITE = {
  name: "EdgeBrain Studios",
  tagline: "We design & build software with an edge.",
  description:
    "EdgeBrain Studios is a software studio specializing in web development, mobile apps, AI automation, and consulting. Based in Lahore, working worldwide.",
  url: "https://edgebrainstudios.com",
} as const;

/**
 * The two canonical node identities in the site's structured-data graph.
 *
 * Every page that wants to talk about the company or the site must reference
 * these strings rather than spell out an IRI or inline a second copy of the
 * node. A one-character difference (`…com#organization` vs `…com/#organization`)
 * declares a second, contradictory company to every consumer of the graph,
 * which is exactly what /about used to do.
 *
 * The nodes themselves are defined once, in src/app/layout.tsx.
 */
export const ORGANIZATION_ID = `${SITE.url}/#organization`;
export const WEBSITE_ID = `${SITE.url}/#website`;

/** Default social share card, generated by src/app/opengraph-image.tsx. */
export const OG_IMAGE_ALT =
  "EdgeBrain Studios — software studio in Lahore building web apps, mobile apps, and AI automation";

export const CONTACT = contentData.contact;

export const NAV_LINKS = [
  { label: "Work", href: "/work" },
  { label: "Services", href: "/services" },
  { label: "Insights", href: "/insights" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
] as const;

export const SERVICES = contentData.services;

/**
 * Canonical URL for each service, keyed by the `number` field in content.json.
 *
 * content.json now stores these same routes in `services[].href`, but that
 * field is editable from the admin panel, and a service page URL is not
 * something a content edit should be able to break. Anything rendering a link
 * to a service should go through `serviceHref` rather than reading `.href`.
 */
export const SERVICE_ROUTES: Record<string, string> = {
  "01": "/services/web-development",
  "02": "/services/mobile-app-development",
  "03": "/services/ai-automation",
  "04": "/services/ai-consulting",
};

export function serviceHref(service: { number: string; href: string }): string {
  return SERVICE_ROUTES[service.number] ?? service.href;
}
export const PROCESS_STEPS = contentData.processSteps;
export const STATS = contentData.stats;
export const PROJECTS = contentData.projects;
/**
 * Empty, and nothing renders it. The six entries this used to hold were
 * invented people at invented companies quoting invented performance numbers.
 * The admin panel still edits this array, so the key stays; the moment it holds
 * a real, attributable review, build a section for it — with the attribution
 * visible, not at 50% opacity.
 */
export const REVIEWS = contentData.reviews;
export const FAQS = contentData.faqs;
export const DIFFERENTIATORS = contentData.differentiators;

/* -------------------------------------------------------------------------- */
/*  Project thumbnail uploads                                                  */
/* -------------------------------------------------------------------------- */

/**
 * Thumbnails uploaded from the admin panel are stored as base64 `data:` URIs
 * inside the content document, not as files.
 *
 * The route used to write into public/images/projects, which — like the old
 * content.json write — silently does nothing on Vercel's read-only runtime
 * filesystem. Even where it appeared to work it was wrong: a file written to
 * the running container disappears on the next deploy, because /public is
 * baked at build time.
 *
 * A data URI has no such problem. It travels with the JSON, survives deploys,
 * needs no bucket, no credentials and no CDN, and `next/image` renders a
 * `data:` src directly (it skips the optimiser for them). The cost is payload
 * size, which is why the cap below is small and enforced on both ends.
 *
 * If the studio ever needs full-bleed case-study imagery rather than a handful
 * of card thumbnails, that is the moment to put real object storage behind
 * this — not the moment to raise the cap.
 */
export const MAX_THUMBNAIL_BYTES = 500 * 1024;

/** Human-readable form of {@link MAX_THUMBNAIL_BYTES}, for UI copy. */
export const MAX_THUMBNAIL_LABEL = "500 KB";

/**
 * Raster formats only. An SVG is a script-carrying document, and the upside of
 * accepting one for a project card does not pay for having to reason about
 * that.
 */
export const ALLOWED_THUMBNAIL_TYPES = [
  "image/png",
  "image/jpeg",
  "image/webp",
  "image/avif",
  "image/gif",
] as const;

export const TECH_LOGOS = [
  "React",
  "Next.js",
  "TypeScript",
  "Node.js",
  "Python",
  "AWS",
  "Tailwind",
  "PostgreSQL",
  "Docker",
  "Figma",
  "OpenAI",
  "Vercel",
] as const;
