import contentData from "@/data/content.json";

export const SITE = {
  name: "EdgeBrain Studios",
  tagline: "We design & build software with an edge.",
  description:
    "EdgeBrain Studios is a software studio specializing in web development, mobile apps, AI automation, and consulting. Based in Lahore, working worldwide.",
  url: "https://edgebrainstudios.com",
} as const;

/**
 * The two canonical node identities in the site's structured-data graph.
 *
 * Every page that wants to talk about the company or the site must reference
 * these strings rather than spell out an IRI or inline a second copy of the
 * node. A one-character difference (`…com#organization` vs `…com/#organization`)
 * declares a second, contradictory company to every consumer of the graph,
 * which is exactly what /about used to do.
 *
 * The nodes themselves are defined once, in src/app/layout.tsx.
 */
export const ORGANIZATION_ID = `${SITE.url}/#organization`;
export const WEBSITE_ID = `${SITE.url}/#website`;

/** Default social share card, generated by src/app/opengraph-image.tsx. */
export const OG_IMAGE_ALT =
  "EdgeBrain Studios — software studio in Lahore building web apps, mobile apps, and AI automation";

export const CONTACT = contentData.contact;

export const NAV_LINKS = [
  { label: "Work", href: "/work" },
  { label: "Services", href: "/services" },
  { label: "Insights", href: "/insights" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
] as const;

export const SERVICES = contentData.services;

/**
 * Canonical URL for each service, keyed by the `number` field in content.json.
 *
 * content.json now stores these same routes in `services[].href`, but that
 * field is editable from the admin panel, and a service page URL is not
 * something a content edit should be able to break. Anything rendering a link
 * to a service should go through `serviceHref` rather than reading `.href`.
 */
export const SERVICE_ROUTES: Record<string, string> = {
  "01": "/services/web-development",
  "02": "/services/mobile-app-development",
  "03": "/services/ai-automation",
  "04": "/services/ai-consulting",
};

export function serviceHref(service: { number: string; href: string }): string {
  return SERVICE_ROUTES[service.number] ?? service.href;
}
export const PROCESS_STEPS = contentData.processSteps;
export const STATS = contentData.stats;
export const PROJECTS = contentData.projects;
/**
 * Empty, and nothing renders it. The six entries this used to hold were
 * invented people at invented companies quoting invented performance numbers.
 * The admin panel still edits this array, so the key stays; the moment it holds
 * a real, attributable review, build a section for it — with the attribution
 * visible, not at 50% opacity.
 */
export const REVIEWS = contentData.reviews;
export const FAQS = contentData.faqs;
export const DIFFERENTIATORS = contentData.differentiators;

export const TECH_LOGOS = [
  "React",
  "Next.js",
  "TypeScript",
  "Node.js",
  "Python",
  "AWS",
  "Tailwind",
  "PostgreSQL",
  "Docker",
  "Figma",
  "OpenAI",
  "Vercel",
] as const;
